name: PyRS
channels:
- conda-forge
- default
- mantid
dependencies:
- python=3.8
- mantidworkbench
- qtpy
- pytest=7.1.2
- pytest-cov=3.0
- pytest-qt=3.3
- uncertainties
- vtk
- flake8
- mypy
- types-six
- versioningit
- conda-build
- conda-verify
- setuptools
- pip:
  - check-wheel-contents
