name: pyrs-rtd-docs

channels:
  - conda-forge
  - mantid/label/nightly
  - mantid

dependencies:
  - python=3.6
  - sphinx
  - pip
  - sphinxcontrib-programoutput
  - uncertainties
  - mock
  - pip:
    - sphinx_rtd_theme>=0.4.1
