name: pyrs-rtd-docs

channels:
  - conda-forge
  - mantid/label/nightly
  - mantid

dependencies:
  - python=3.6
  - sphinx
  - pip
  - sphinx.ext.autodoc
  - sphinx.ext.todo
  - sphinxcontrib.programoutput
  - sphinx.ext.mathjax
  - mantid-workbench>=4.2
  - uncertainties
  - scipy>=0.18
  - qtpy
  - h5py
  - vtk
  - pip:
    - sphinx_rtd_theme>=0.4.1
