name: PyRS CI

on: [push, pull_request]

env:
  TRIGGER_URL: "https://code.ornl.gov/api/v4/projects/6012/trigger/pipeline"

jobs:

  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 100

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: mantid,mantid/label/nightly,conda-forge
          environment-file: environment.yml

      - name: Apt install deps
        run: |
          sudo apt update
          sudo apt-get install xvfb freeglut3-dev libglu1-mesa

      - name: Lint
        run: flake8 . --count

      - name: mypy
        run: mypy pyrs scripts tests

      - name: Mantid pre-requisites - create a properties file that turns off network access
        run: |
          mkdir ~/.mantid
          echo "CheckMantidVersion.OnStartup=0" > ~/.mantid/Mantid.user.properties
          echo "UpdateInstrumentDefinitions.OnStartup=0" >> ~/.mantid/Mantid.user.properties
          echo "usagereports.enabled=0" >> ~/.mantid/Mantid.user.properties

      - name: Test mantid/workbench
        run: |
          python -c "import mantid"
          python -c "import qtpy"
          python -c "import mantidqt"
          xvfb-run -a mantidworkbench --help

      - name: Run PyRS tests
        run: xvfb-run --server-args="-screen 0 640x480x24" -a pytest --cov=pyrs --cov-report=xml --cov-report=term tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  build-conda:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: mantid,mantid/label/nightly,conda-forge
          environment-file: environment.yml

      - name: Build conda libraray
        shell: bash -l {0}
        run: |
          echo GITHUB REF ${{ github.ref }}
          conda install -y anaconda-client conda-build conda-verify
          cd conda.recipe
          conda build --output-folder . . -c mantid/label/nightly

  build-conda-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Build conda libraray
        shell: bash -l {0}
        run: |
          echo GITHUB REF ${{ github.ref }}
          conda install -y anaconda-client conda-build conda-verify
          cd conda.recipe
          conda build --output-folder . . -c neutrons -c mantid/label/nightly

  build-conda-nightly:
    if: ${{ github.ref == 'refs/heads/next' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Build conda libraray
        shell: bash -l {0}
        run: |
          echo GITHUB REF ${{ github.ref }}
          conda install -y anaconda-client conda-build conda-verify
          cd conda.recipe
          conda build --output-folder . . -c neutrons -c mantid/label/nightly

  build-conda-rc:
    if: ${{ github.ref == 'refs/heads/qa' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Build conda libraray
        shell: bash -l {0}
        run: |
          echo GITHUB REF ${{ github.ref }}
          conda install -y anaconda-client conda-build conda-verify
          cd conda.recipe
          conda build --output-folder . . -c neutrons -c mantid/label/nightly

  trigger-prod-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - name: ornl-trigger
        run:
          echo "Launching gitlab webhook to deploy ${GITHUB_REF_NAME} from ${GITHUB_REF}"
          curl --fail-with-body -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref="${GITHUB_REF_NAME}" ${TRIGGER_URL} | jq '. | del( .user )' ; exit ${PIPESTATUS[0]}

  trigger-qa-deploy:
    if: ${{ github.ref == 'refs/heads/qa' }}
    runs-on: ubuntu-22.04
    steps:
      - name: ornl-trigger
        run: |
          echo "Launching gitlab webhook to deploy ${GITHUB_REF_NAME} from ${GITHUB_REF}"
          curl --fail-with-body -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref="${GITHUB_REF_NAME}" ${TRIGGER_URL} | jq '. | del( .user )' ; exit ${PIPESTATUS[0]}
