name: PyRS CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

env:
  TRIGGER_URL: "https://code.ornl.gov/api/v4/projects/6012/trigger/pipeline"

jobs:

  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 100

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: mantid,mantid/label/nightly,conda-forge
          environment-file: environment.yml

      - name: Apt install deps
        run: |
          sudo apt update
          sudo apt-get install xvfb freeglut3-dev libglu1-mesa

      - name: Lint
        run: flake8 . --count

      - name: mypy
        run: mypy pyrs scripts tests

      - name: Mantid pre-requisites - create a properties file that turns off network access
        run: |
          mkdir ~/.mantid
          echo "CheckMantidVersion.OnStartup=0" > ~/.mantid/Mantid.user.properties
          echo "UpdateInstrumentDefinitions.OnStartup=0" >> ~/.mantid/Mantid.user.properties
          echo "usagereports.enabled=0" >> ~/.mantid/Mantid.user.properties

      - name: Test mantid/workbench
        run: |
          python -c "import mantid"
          python -c "import qtpy"
          python -c "import mantidqt"

      - name: Run PyRS tests
        run: xvfb-run --server-args="-screen 0 640x480x24" -a pytest --cov=pyrs --cov-report=xml --cov-report=term tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  trigger-deploy:
    runs-on: ubuntu-22.04
    needs: [ci]
    # only trigger deploys from protected branches
    if: ${{ github.ref_protected || github.ref_type == 'tag' }}
    steps:
      - name: Determine Environment
        uses: neutrons/branch-mapper@main
        id: conda_env_name
        with:
          prefix: pyrs

      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 6012
          ref_name: master
          variables: |
            PLAY="update"
            CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

      - name: Annotate commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
