name: Deploy to ORNL
on:
  workflow_run:
    workflows: [PyRS CI]
    branches: [next, main]
    types: [completed]

jobs:
  ornl-trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Launching gitlab webhook to deploy ${GITHUB_REF_NAME} from ${GITHUB_REF}"
          # post to projects/6012 ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          curl --fail-with-body -sX POST -F token=not_a_token -F ref="${GITHUB_REF_NAME}" ${{ secrets.GITLAB_TRIGGER_URL }} | jq '. | del( .user )' ; exit ${PIPESTATUS[0]}
